plugins {
    id 'java'
}

group = 'org.freeplane.plugin.chat'
version = '1.12.2'

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':freeplane')
    lib 'dev.langchain4j:langchain4j-open-ai:1.1.0'
    lib 'dev.langchain4j:langchain4j-anthropic:1.1.0-rc1'
    lib 'dev.langchain4j:langchain4j-ollama:1.1.0-rc1'
    lib 'dev.langchain4j:langchain4j:1.1.0'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

test {
    useJUnitPlatform()
}